"""baseline

Revision ID: b0ab0e01d611
Revises: 
Create Date: 2026-06-02 14:16:35.348395
"""
from alembic import op
import sqlalchemy as sa


revision = 'b0ab0e01d611'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commune_pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commune', sa.String(length=120), nullable=False),
    sa.Column('canton', sa.String(length=8), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_authority', sa.String(length=300), nullable=True),
    sa.Column('valid_as_of', sa.String(length=40), nullable=True),
    sa.Column('review_due', sa.String(length=40), nullable=True),
    sa.Column('ingested_at', sa.String(length=40), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commune_pack')),
    sa.UniqueConstraint('commune', 'canton', 'version', name=op.f('uq_commune_pack_commune'))
    )
    op.create_table('org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org'))
    )
    op.create_table('ingestion_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commune_pack_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['commune_pack_id'], ['commune_pack.id'], name=op.f('fk_ingestion_job_commune_pack_id_commune_pack')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_job'))
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phase_code', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('canton', sa.String(length=8), nullable=False),
    sa.Column('commune', sa.String(length=120), nullable=False),
    sa.Column('knowledge_regime', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], name=op.f('fk_project_org_id_org')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project')),
    sa.UniqueConstraint('org_id', 'project_id', name=op.f('uq_project_org_id'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], name=op.f('fk_user_org_id_org')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('org_id', 'email', name=op.f('uq_user_org_id'))
    )
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('formula', sa.String(length=300), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_claim_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim'))
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('file_ref', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('valid_as_of', sa.String(length=40), nullable=True),
    sa.Column('retrieved_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_evidence_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('actor_role', sa.String(length=60), nullable=False),
    sa.Column('phase_code', sa.String(length=8), nullable=False),
    sa.Column('mutating', sa.Boolean(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_ledger_entry_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entry'))
    )
    op.create_table('regulatory_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('canton', sa.String(length=8), nullable=False),
    sa.Column('commune', sa.String(length=120), nullable=False),
    sa.Column('selected_at', sa.String(length=40), nullable=False),
    sa.Column('active_pack_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_regulatory_route_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulatory_route'))
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_report_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report'))
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('locator', sa.String(length=500), nullable=True),
    sa.Column('valid_as_of', sa.String(length=40), nullable=True),
    sa.Column('retrieved_at', sa.String(length=40), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_source_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source'))
    )
    op.create_table('approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_entry_id', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('approved_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entry.id'], name=op.f('fk_approval_ledger_entry_id_ledger_entry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval')
    op.drop_table('source')
    op.drop_table('report')
    op.drop_table('regulatory_route')
    op.drop_table('ledger_entry')
    op.drop_table('evidence')
    op.drop_table('claim')
    op.drop_table('user')
    op.drop_table('project')
    op.drop_table('ingestion_job')
    op.drop_table('org')
    op.drop_table('commune_pack')
    # ### end Alembic commands ###
