"""add_user_api_token

Revision ID: bd0bea40e23d
Revises: b0ab0e01d611
Create Date: 2026-06-02 14:31:14.296638
"""
from alembic import op
import sqlalchemy as sa


revision = 'bd0bea40e23d'
down_revision = 'b0ab0e01d611'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=96), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_api_token'), ['api_token'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_api_token'), type_='unique')
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###
